### ISSUE TITLE
jaccard in lsh.adjacency_list() has error

### ISSUE THREAD

**Issue by bihappywater** [justinnbt/SnaPy#6]
Hallo, 
I am trying to use SnaPy,  very interesting topic. Thanks!
When I play a bit, find that jaccard argument in lsh.adjacency_list() doesn't work. 
Using the same quick example, if i want try to do 
print(lsh.adjacency_list(sensitivity = 1, jaccard = .5, keep_jaccard  =True, average_jaccard = True))
it will throw me an error message:
NoneType object is not subscriptable,  
in line 219, in adjacency_list
in line 69, in _jaccard_similarity
..
One more quesiton:
When we use MinHash, is that possible we do the minhash based on tokenize_words, not in shingles?

Besides, one suggestion
It will be highly appreciated to have more example for using lsh or transfer them to the real data.  

Thanks again for building up this package!

**Comment by justinnbt** [comment]
Thanks for finding this bug with the adjacency_list method and taking the time to raise an issue!
I will have a look tonight and see if I can replicate it and fix it.

For MinHash it wouldn't be too hard to tokenize_words on whitespace, I will have a think about how best to add this.

We are currently working on building out the documentation for this, including more examples of all the possible uses of the library.

Thanks!

**Comment by justinnbt** [comment]
The bug with lsh.adjacency_list has been fixed and the edge functionality of the lsh.adjacency_list method split off into an lsh.edge_list method. 
Readme has been updated with more examples and full API documentation.
I have also added the ability to tokenize words as well as characters.
